config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users, only: [:index, :create] do
    collection do
      post :signin
      get :signup
    end
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates_presence_of :description
  validate :valid_schedule?

  protected

  def valid_schedule?
    return if start_date.nil? || end_date.nil?
    errors.add(:schedule, "is not valid") if start_date > end_date
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :tasks
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates_format_of :email, with: VALID_EMAIL_REGEX
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    else
      nil
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :load_user

  def new
    @task = @user.tasks.new
  end

  def index
    load_collection
  end

  def edit
    load_resource
  end

  def show
    load_resource
    render 'edit'
  end

  def create
    @task = @user.tasks.new(task_params)
    if @task.save
      load_collection
      render 'tasks/index'
    else
      render 'new'
    end
  end

  def update
    load_resource
    if @task.update_attributes(task_params)
      load_collection
    else
      render 'edit'
    end
  end

  protected
  def load_collection
    @tasks = @user.tasks
  end

  def load_resource
    @task = @user.tasks.find_by(id: params[:id])
  end

  def load_user
    @user = current_user
  end

  def task_params
    params.require(:task).permit(:user_id, :description, :start_date, :end_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
    render :index
  end

  def signin
    @user = User.find_by(email: user_params[:email])
    if @user&.authenticate(user_params[:password])
      @tasks = @user.tasks
      session.clear
      session[:user_id] = @user.id
      render 'tasks/index'
    else
      flash[:alert] = 'Invalid email or password'
      @user = User.new
      render :index
    end
  end

  def signup
    @user = User.new
    render :signup
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @tasks = @user.tasks
      render 'tasks/index'
    else
      render :signup
    end
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div data-alert class="alert-box <%= key %>">
        <%= value %>
      </div>
    <% end %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for([@user, @task]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :description %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', title: @task&.description %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<%= link_to 'New task', new_user_task_path(@user), :class => 'btn btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Start</th>
      <th>End</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.description, [@user, task] %></td>
        <td><%= task.start_date %></td>
        <td><%= task.end_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<%= render 'form', :title => "New Task" %>

app/views/users/index.html.erb
<h1>Login</h1>
<%= simple_form_for @user, url: signin_users_path, method: :post do |f| %>
  <%= f.error_notification %>
  <%= f.input :email %>
  <%= f.input :password %>

  <%= f.button :submit, 'Login' %>
<% end %>
<%= link_to "Sign up", signup_users_path %>

app/views/users/signup.html.erb
<h1>Sign up</h1>
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit, 'Register' %>
<% end %>
<%= link_to "Go back", root_path %>